version: '2'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql_www
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cat
    volumes:
      - ./users.sql:/docker-entrypoint-initdb.d/users.sql
      - ./info.sql:/docker-entrypoint-initdb.d/info.sql
  web:
    image: vulhub/thinkphp:5.0.9
    container_name: web_www
    links:
      - mysql
    depends_on:
      - mysql
    ports:
      - "80:80"
    volumes:
      - ./www/:/var/www/
